version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
    networks:
      - bakmie_network
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: bakmie_frontend
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: always
    networks:
      - bakmie_network

  # Development service (optional, can be commented out in production)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bakmie_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - bakmie_network

networks:
  bakmie_network:
    name: bakmie_network
    driver: bridge 